name: justplaymobile
description: Una aplicación de gestión de eventos deportivos con características similares a JustPlay, incluyendo reserva de canchas, registro de jugadores y estadísticas en tiempo real.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^6.4.0
  bloc: ^8.1.2
  connectivity_checker: ^1.1.0
  country_state_city_picker: ^1.2.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed: 2.4.1
  freezed_annotation: 2.4.1
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_screenutil: 5.7.0
  get_it: 7.6.0
  http: 0.13.6
  intl: 0.17.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  url_launcher: 6.1.11
  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^6.2.0
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - assets/img/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Bold.ttf
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat/Caveat-SemiBold.ttf
flutter_intl:
  enabled: true
